-- ============================================================
--  basedatos/procedures.sql — PUNTERO
--
--  Este archivo contenía sólo sp_registrar_usuario. Las rutinas del
--  proyecto crecieron a 14 (4 funciones, 5 procedimientos y 5
--  triggers) y ahora viven todas juntas en:
--
--      basedatos/rutinas.sql        ← el archivo canónico
--
--  instalar.sql lleva una copia para que la instalación limpia siga
--  siendo un solo archivo, y herramientas/actualizar.bat ejecuta
--  rutinas.sql sobre las bases ya existentes.
-- ============================================================
